### ISSUE TITLE
[Command Line] Error importing CondorcetFormat: Argument #1 ($callBack) must be of type Closure

### ISSUE THREAD

**Issue by julien-boudry** [julien-boudry/Condorcet#147]
I'm getting an error with the .cvotes file. Here is my attempt to use the [first example](https://github.com/CondorcetVote/CondorcetElectionFormat#valid) you wrote. The stack trace doesn't involve any files that I modified.

```
[liam@Liam-Manjaro-Desktop Condorcet]$ ./bin/condorcet election --import-condorcet-election-format=myTests/Julians-Beautiful-Election.cvotes -lr Schulze Borda Minimax

     _/_/_/                            _/                                            _/   
  _/          _/_/    _/_/_/      _/_/_/    _/_/    _/  _/_/    _/_/_/    _/_/    _/_/_/_/
 _/        _/    _/  _/    _/  _/    _/  _/    _/  _/_/      _/        _/_/_/_/    _/     
_/        _/    _/  _/    _/  _/    _/  _/    _/  _/        _/        _/          _/      
 _/_/_/    _/_/    _/    _/    _/_/_/    _/_/    _/          _/_/_/    _/_/_/      _/_/   

==========================================================================================

Version: 4.5.0-(dev)-g9e977045 || Author: Julien Boudry and contributors || Homepage: https://github.com/julien-boudry/Condorcet

PHP Fatal error:  Uncaught TypeError: CondorcetPHP\Condorcet\Console\Commands\ElectionCommand::parseFromCondorcetElectionFormat(): Argument #1 ($callBack) must be of type Closure, null given, called in /home/liam/src2/Condorcet/src/Console/Commands/ElectionCommand.php on line 356 and defined in /home/liam/src2/Condorcet/src/Console/Commands/ElectionCommand.php:742
Stack trace:
#0 /home/liam/src2/Condorcet/src/Console/Commands/ElectionCommand.php(356): CondorcetPHP\Condorcet\Console\Commands\ElectionCommand->parseFromCondorcetElectionFormat()
#1 /home/liam/src2/Condorcet/src/Console/Commands/ElectionCommand.php(382): CondorcetPHP\Condorcet\Console\Commands\ElectionCommand->importInputsData()
#2 /home/liam/src2/Condorcet/vendor/symfony/console/Command/Command.php(312): CondorcetPHP\Condorcet\Console\Commands\ElectionCommand->execute()
#3 /home/liam/src2/Condorcet/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run()
#4 /home/liam/src2/Condorcet/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#5 /home/liam/src2/Condorcet/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#6 /home/liam/src2/Condorcet/src/Console/CondorcetApplication.php(30): Symfony\Component\Console\Application->run()
#7 /home/liam/src2/Condorcet/bin/condorcet.php(32): CondorcetPHP\Condorcet\Console\CondorcetApplication::run()
#8 /home/liam/src2/Condorcet/bin/condorcet(3): require('...')
#9 {main}
  thrown in /home/liam/src2/Condorcet/src/Console/Commands/ElectionCommand.php on line 742
```

_Originally posted by @LiamM32 in https://github.com/julien-boudry/Condorcet/discussions/141#discussioncomment-6181465_

**Comment by julien-boudry** [comment]
Actually, I don't reproduce. Which PHP version do you use @LiamM32 ?

**Comment by julien-boudry** [comment]
Can you try again with the last commit from 4.5 branch?

**Comment by LiamM32** [comment]
I have PHP 8.2.6.
I have the php-sqlite package installed in Manjaro. Also version 8.2.6. It contains the file `/usr/lib/php/modules/pdo_sqlite.so`, so it's probably what you are referring to.

I will update to the new commit now and try again.

**Comment by LiamM32** [comment]
Before updating, I once again did the command `./bin/condorcet election --import-condorcet-election-format=myTests/Julians-Beautiful-Election.cvotes -lr Schulze Borda Minimax`. It failed.

Then I updated with `git pull`.

I repeated the first command. It immediately worked. Thank you.

**Comment by julien-boudry** [comment]
Definitely a PHP extension error, but my fault: the check for existing extension was deficient in this particular case in the command line version.
PHP is close to being a strongly typed language now, it's was an indirect but real interesting bug.
