### ISSUE TITLE
Pb wit symphony

### ISSUE THREAD

**Issue by chupinmaxime** [julien-boudry/Condorcet#72]
| Q                   | A
| --------------------| ---------------
| Type                | Bug
| Condorcet version   | 2.2.3
| PHP version         | 7.4.3
| Installation Method | Composer 

Using 
```
./vendor/bin/condorcet election --candidates listeLigne.txt --votes voteCA.txt -r
``` 
I get the following error:
```
PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /home/mc/Bureau/Condorcet-master/Condorcet/vendor/julien-boudry/condorcet/lib/Console/Commands/ElectionCommand.php:254
Stack trace:
#0 /home/mc/Bureau/Condorcet-master/Condorcet/vendor/symfony/console/Command/Command.php(299): CondorcetPHP\Condorcet\Console\Commands\ElectionCommand->execute()
#1 /home/mc/Bureau/Condorcet-master/Condorcet/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run()
#2 /home/mc/Bureau/Condorcet-master/Condorcet/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand()
#3 /home/mc/Bureau/Condorcet-master/Condorcet/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#4 /home/mc/Bureau/Condorcet-master/Condorcet/vendor/julien-boudry/condorcet/lib/Console/CondorcetApplication.php(25): Symfony\Component\Console\Application->run()
#5 /home/mc/Bureau/Condorcet-master/Condorcet/vendor/julien-boudry/condorcet/bin in /home/mc/Bureau/Condorcet-master/Condorcet/vendor/julien-boudry/condorcet/lib/Console/Commands/ElectionCommand.php on line 254
```

My files are the following (on a simple test, everything works well):

listeLigne.txt
```
association-gut.eu;association-gut.fr;association-gut.info;association-gut.net;association-gut.org;association-gutenberg.eu;association-gutenberg.info;associationgutenberg.eu;associationgutenberg.fr;associationgutenberg.info;associationgutenberg.net;associationgutenberg.org;asso-gut.eu;asso-gut.fr;asso-gut.info;asso-gut.net;asso-gut.org;asso-gutenberg.eu;asso-gutenberg.info;fr.tug.org;francogut.eu;francogut.fr;francogut.info;francogut.net;francogut.org;francotug.eu;francotug.fr;francotug.info;francotug.net;francotug.org;groupetex.eu;groupetex.fr;groupetex.info;groupetex.net;groupetex.org;grtex.eu;grtex.fr;grtex.info;grtex.net;grtex.org;grutex.eu;grutex.fr;grutex.info;grutex.net;grutex.org;gutambergue.eu;gutambergue.fr;gutambergue.info;gutambergue.net;gutambergue.org;gutanbergue.eu;gutanbergue.fr;gutanbergue.info;gutanbergue.net;gutanbergue.org;gut-asso.eu;gut-asso.fr;gut-asso.info;gut-asso.net;gut-asso.org;gut-association.eu;gut-association.fr;gut-association.info;gut-association.net;gut-association.org;gutemberg.eu;gutemberg.info;gutenber.eu;gutenber.fr;gutenber.info;gutenber.net;gutenberg.fr;gutenberg-asso.eu;gutenberg-asso.fr;gutenberg-asso.info;gutenberg-asso.net;gutenberg-asso.org;gutenberg-association.eu;gutenberg-association.fr;gutenberg-association.info;gutenberg-association.net;gutenberg-association.org;gutenberg-france.eu;gutenberg-france.fr;gutenberg-france.info;gutenberg-france.net;gutenberg-france.org;gutenberg-latex.eu;gutenberg-latex.fr;gutenberg-latex.info;gutenberg-latex.net;gutenberg-latex.org;gutenberglatex.eu;gutenberglatex.fr;gutenberglatex.info;gutenberglatex.net;gutenberglatex.org;gutenberg-tex.eu;gutenberg-tex.fr;gutenberg-tex.info;gutenberg-tex.net;gutenberg-tex.org;gutenferg.eu;gutenferg.fr;gutenferg.info;gutenferg.net;gutenferg.org;gutenfr.eu;gutenfr.fr;gutenfr.info;gutenfr.net;gutenfr.org;gutenvers.eu;gutenvers.fr;gutenvers.info;gutenvers.net;gutenvers.org;gutex.fr;gutexberg.eu;gutexberg.fr;gutexberg.info;gutexberg.net;gutexberg.org;gut-fr.eu;gut-fr.fr;gut-fr.info;gut-fr.net;gut-fr.org;gut-latex.eu;gut-latex.fr;gut-latex.info;gut-latex.net;gut-latex.org;gutnber.eu;gutnber.fr;gutnber.info;gutnber.net;gutnber.org;gutnberg.eu;gutnberg.fr;gutnberg.info;gutnberg.net;gut-tex.eu;gut-tex.fr;gut-tex.info;gut-tex.net;gut-tex.org;jgutenberg.eu;jgutenberg.fr;jgutenberg.info;jgutenberg.net;jgutenberg.org;texgutenberg.eu;texgutenberg.fr;texgutenberg.info;texgutenberg.net;texgutenberg.org;tug-fr.eu;tug-fr.fr;tug-fr.info;tug-fr.net;tug-fr.org;tug-french.eu;tug-french.fr;tug-french.info;tug-french.net;tug-french.org
```

and voteCA.txt
```
associationgutenberg.fr>associationgutenberg.net>associationgutenberg.org>gutenberg-asso.fr>gutenberg-asso.net>gutenberg-asso.org>gutenberg-association.fr>gutenberg-association.net>gutenberg-association.org>gut-asso.fr>gut-asso.net>gut-asso.org>association-gut.fr>association-gut.net>association-gut.org;
association-gutenberg.info>gutenberg-association.fr>gutenberg-association.org>gutenberg-association.info>gutenberg-association.net>asso-gutenberg.info>gutenberg-asso.fr>gutenberg-asso.org>gutenberg-asso.info>gutenberg-asso.net>gutenberg-latex.fr>gutenberg-latex.org>gutenberg-latex.info>gutenberg-latex.net>gutenberg-tex.fr>gutenberg-tex.org>gutenberg-tex.info>gutenberg-tex.net>associationgutenberg.fr>associationgutenberg.org>associationgutenberg.info>associationgutenberg.net;
associationgutenberg.fr>gutenberg-association.fr>gutenberg-latex.fr>association-gutenberg.info>associationgutenberg.org>associationgutenberg.net>associationgutenberg.info>gutenberg-latex.info>gutenberg-latex.net>gutenberg-latex.org>gutenberg-association.org>gutenberg-association.net>gutenberg-association.info>tug-fr.org>tug-fr.net>groupetex.org;
association-gutenberg.fr>association-gut.fr>asso-gutenberg.fr>asso-gut.fr>gut-asso.fr>gutenberg-association.fr>association-gutenberg.org>association-gut.org>asso-gutenberg.org>asso-gut.org>gut-asso.org>gutenberg-association.org>gutenberg-asso.org;
asso-gut.org>asso-gut.fr>gut-asso.org>gut-asso.fr>association-gut.org>gut-association.org>gut-association.fr>gut-latex.org>gut-latex.fr>gutenberg-latex.org>gutenberg-latex.fr>gutenberg-tex.org>gutenberg-tex.fr>asso-gutenberg.eu
association-gut.fr>association-gut.org>association-gutenberg.fr>association-gutenberg.org>asso-gut.fr>asso-gut.org>asso-gutenberg.fr>asso-gutenberg.org>gutenberg.fr>gutenberg.org>gutenberg-asso.fr>gutenberg-asso.org>gutenberg-association.fr>gutenberg-association.org;
gutenberg.fr>gutex.fr>groupetex.fr>groupetex.org>gutenberg.eu.org>jgutenberg.eu>jgutenberg.fr>jgutenberg.org>grtex.fr>grutex.org;
associationgutenberg.fr>associationgutenberg.org>gutenberg-association.fr>gutenberg-association.org>gutenberg-asso.fr>gutenberg-asso.org>gutenberg-tex.fr>gutenberg-tex.org>association-gut.fr>association-gut.org;
associationgutenberg.fr>associationgutenberg.org>gutenberg-association.fr>gutenberg-association.org>gutenberg-asso.fr>gutenberg-asso.org>gutenberg-asso.fr>gutenberg-asso.org>gutenberg-latex.fr>gutenberg-latex.org>gutenberg-tex.fr>gutenberg-tex.org>gutenberg-latex.net>gutenberg-tex.net>association-gut.fr>association-gut.org>gut-asso.fr>gut-asso.org
```

Any idea? Maybe is it due to the dots and the dashes in each domain name?

Thx

**Comment by chupinmaxime** [comment]
I tried with simple letters instead of domain name, and I have the same error.

**Comment by chupinmaxime** [comment]
The problem comes from option `-r`. So I can use the program with files but without `-r` (`-l` works well).

**Comment by julien-boudry** [comment]
Thanks @chupinmaxime : I look at that in few minutes. Did you test it on 3.x branch alorso?

**Comment by julien-boudry** [comment]
Verified on all versions including master.

**Comment by julien-boudry** [comment]
Introduced on 87e0e47d2317

**Comment by julien-boudry** [comment]
Hi @chupinmaxime and thanks for that,

Just release 2.2.4 with this fix. Version 3.1.2 will follows soon after another bugfix.
